"""Modelo tipado do `graph_json` de um flow + validação compartilhada (RF-302/307, ADR-024).

Uma implementação, dois consumidores (spec F3 §2.1): a API valida no save (422) e o runtime
valida ao montar a definição *staged* do hot-swap. Núcleo puro — nada de SQLAlchemy nem de
`services/` aqui: o chamador traduz linhas do banco em `TagRef`.

Pacote dividido por responsabilidade (débito 6 do plano F4a — teto de linhas por arquivo):

- `parse.py` cuida da **forma** (estrutura e tipagem estática do JSONB) e levanta
  `GraphParseError` com a lista completa de problemas;
- `validate.py` cuida da **semântica que precisa de contexto** (tags do projeto, Ts do
  flow, topologia) e nunca levanta por conteúdo de grafo — devolve `ValidationResult`.

Import público inalterado: `from ottima_core.flowgraph import ...` continua funcionando para
todo consumidor; ninguém fora deste pacote deve importar `ottima_core.flowgraph.parse` ou
`ottima_core.flowgraph.validate` diretamente.
"""

from ottima_core.flowgraph.mpc_config import (
    MPC_FIXED_OUTPUT_PORTS,
    MPC_PORT_AUTO,
    MPC_PORT_LOCAL,
    ConstraintObjective,
    ConstraintVar,
    CvObjective,
    CvVar,
    DvVar,
    EconomicsConfig,
    Horizons,
    Limits,
    ModeValues,
    MpcConfig,
    MpcVariables,
    MvObjective,
    MvVar,
    PairModel,
    PidBinding,
    Range,
    RowKind,
    SolverName,
    TargetMode,
    derive_horizons,
    economics_config_hash,
    gain_model_hash,
    mpc_state_dimension,
    optimization_enabled,
)
from ottima_core.flowgraph.parse import (
    BUS_KEY_PATTERN,
    BUS_TYPES,
    MAX_SCRIPT_PORTS,
    NODE_TYPES,
    TFS_DEFAULT_Y0,
    BusKeyConfig,
    ConstantConfig,
    DeadTimeConfig,
    FirstOrderConfig,
    FlowEdge,
    FlowGraph,
    FlowNode,
    FuzzyConfig,
    FuzzyLoopConfig,
    GraphParseError,
    IntegratorConfig,
    IopdtParams,
    KalmanConfig,
    LeadLagConfig,
    LoopBaseConfig,
    MpcRawConfig,
    NodeConfig,
    NodeType,
    PidConfig,
    PidLoopConfig,
    Position,
    ScalerConfig,
    ScriptConfig,
    SopdtParams,
    TagConfig,
    TfsConfig,
    TfsElement,
    loop_structural,
    parse_graph,
)
from ottima_core.flowgraph.validate import (
    LOOP_TYPES,
    MAX_DELAY_SAMPLES,
    NodePorts,
    PortKind,
    TagRef,
    ValidationResult,
    bus_publish_keys,
    check_script_code,
    graph_ports,
    validate_graph,
)

__all__ = [
    "MAX_DELAY_SAMPLES",
    "MAX_SCRIPT_PORTS",
    "MPC_FIXED_OUTPUT_PORTS",
    "MPC_PORT_AUTO",
    "LOOP_TYPES",
    "MPC_PORT_LOCAL",
    "NODE_TYPES",
    "TFS_DEFAULT_Y0",
    "BUS_KEY_PATTERN",
    "BUS_TYPES",
    "BusKeyConfig",
    "ConstraintObjective",
    "ConstraintVar",
    "ConstantConfig",
    "CvObjective",
    "CvVar",
    "DvVar",
    "DeadTimeConfig",
    "EconomicsConfig",
    "FirstOrderConfig",
    "FlowEdge",
    "FlowGraph",
    "FlowNode",
    "FuzzyConfig",
    "GraphParseError",
    "IntegratorConfig",
    "Horizons",
    "IopdtParams",
    "KalmanConfig",
    "LeadLagConfig",
    "Limits",
    "FuzzyLoopConfig",
    "ModeValues",
    "LoopBaseConfig",
    "MpcConfig",
    "MpcRawConfig",
    "MpcVariables",
    "MvObjective",
    "MvVar",
    "NodeConfig",
    "NodeType",
    "NodePorts",
    "PairModel",
    "PidBinding",
    "PidConfig",
    "PidLoopConfig",
    "PortKind",
    "Position",
    "Range",
    "RowKind",
    "ScriptConfig",
    "ScalerConfig",
    "SolverName",
    "SopdtParams",
    "TagConfig",
    "TagRef",
    "TargetMode",
    "loop_structural",
    "TfsConfig",
    "TfsElement",
    "ValidationResult",
    "bus_publish_keys",
    "check_script_code",
    "derive_horizons",
    "economics_config_hash",
    "gain_model_hash",
    "graph_ports",
    "mpc_state_dimension",
    "optimization_enabled",
    "parse_graph",
    "validate_graph",
]
