/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Sempre 200: a degradação vai no corpo (spec §3.3-3).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Workers
         * @description Agrega os 3 workers em paralelo, 1 thread cada (F5R-09: urllib stdlib, sem httpx em
         *     produção).
         */
        get: operations["health_workers_api_health_workers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_users__user_id__get"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Projetos nascem inativos (ADR-017): a ativação é um passo explícito.
         */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Project
         * @description Transação única: desativa o atual e ativa o alvo (ADR-017; índice parcial garante 1 ativo).
         *
         *     F1 apenas persiste; a partir da F3 este endpoint também encerra a execução do projeto
         *     anterior via `flow.commands` (gancho registrado no spec §6.2). Reativar o projeto que já
         *     é o ativo continua respondendo 200 com o projeto, mas **não** republica o evento.
         */
        post: operations["activate_project_api_projects__project_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Project
         * @description Arquivo de projeto (bundle) para portabilidade entre instalações (spec §3.1).
         *
         *     `require_admin`: mesmo sem segredos, o bundle revela a topologia OPC completa da
         *     planta (RF-102, PRD §2). Exporta **qualquer** projeto por id, não só o ativo.
         */
        get: operations["export_project_api_projects__project_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Project
         * @description Import de projeto (spec §3.2, RF-103): quatro camadas de validação, a maioria em
         *     memória e antes de qualquer insert. As duas exceções — nome de projeto duplicado (só o
         *     banco responde) e a camada 4 (que precisa dos ids gerados pelo insert de conexões/tags
         *     para traduzir o grafo) — inserem via `flush()` e desfazem com `rollback()` se falharem;
         *     o `commit()` só acontece depois que as quatro camadas passam.
         */
        post: operations["import_project_api_projects_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_api_connections_get"];
        put?: never;
        /** Create Connection */
        post: operations["create_connection_api_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection */
        get: operations["get_connection_api_connections__connection_id__get"];
        put?: never;
        post?: never;
        /** Delete Connection */
        delete: operations["delete_connection_api_connections__connection_id__delete"];
        options?: never;
        head?: never;
        /** Update Connection */
        patch: operations["update_connection_api_connections__connection_id__patch"];
        trace?: never;
    };
    "/api/connections/{connection_id}/server-certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Server Certificate
         * @description Confia no certificado do servidor (ADR-021): corpo bruto DER ou PEM, gravado como DER.
         *
         *     O certificado vem no corpo da request (`application/octet-stream`,
         *     `application/x-pem-file` ou `application/pkix-cert`), não em multipart: um upload de
         *     campo único não justifica a dependência extra de parsing de formulário.
         *
         *     Emite `connection_updated` porque `server_cert_file` também é campo do PATCH: a mesma
         *     mudança de estado não pode ser auditada por uma rota e silenciosa pela outra. O evento é
         *     ainda a dica de reconciliação do worker (spec §2.2-1), e trocar o certificado confiado é
         *     justamente o que derruba o canal seguro.
         */
        post: operations["set_server_certificate_api_connections__connection_id__server_certificate_post"];
        /**
         * Clear Server Certificate
         * @description Deixa de confiar no certificado do servidor. Idempotente: 204 mesmo sem o arquivo.
         *
         *     Só emite quando houve mudança de estado — arquivo removido ou coluna limpa. Repetir o
         *     DELETE numa conexão que já não confia em nada é no-op, e no-op não é evento.
         */
        delete: operations["clear_server_certificate_api_connections__connection_id__server_certificate_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description Lista tags; `direction` inválida apenas não casa nada (sem 422 no filtro).
         */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tag */
        get: operations["get_tag_api_tags__tag_id__get"];
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_api_tags__tag_id__delete"];
        options?: never;
        head?: never;
        /** Update Tag */
        patch: operations["update_tag_api_tags__tag_id__patch"];
        trace?: never;
    };
    "/api/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Flows
         * @description Lista leve (spec §5.1): `graph_json` só sai no detalhe.
         */
        get: operations["list_flows_api_flows_get"];
        put?: never;
        /**
         * Create Flow
         * @description Flow nasce parado (ADR-017) e com grafo vazio; o desenho chega pelo PUT.
         */
        post: operations["create_flow_api_flows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{flow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Flow */
        get: operations["get_flow_api_flows__flow_id__get"];
        /**
         * Update Flow
         * @description Valida o grafo antes de gravar (spec §5.2); avisos de inversão não bloqueiam (RF-307).
         *
         *     `graph_json` e `ts_seconds` ausentes mantêm o que já está salvo — o diálogo de
         *     propriedades troca nome/Ts sem carregar o desenho. Qualquer que seja a combinação, o par
         *     (grafo, Ts) EFETIVO é revalidado junto: trocar só o Ts pode estourar o teto de atraso de
         *     um TFS que era válido no Ts anterior.
         */
        put: operations["update_flow_api_flows__flow_id__put"];
        post?: never;
        /** Delete Flow */
        delete: operations["delete_flow_api_flows__flow_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{flow_id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deploy Flow */
        post: operations["deploy_flow_api_flows__flow_id__deploy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{flow_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Flow */
        post: operations["stop_flow_api_flows__flow_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/{flow_id}/{block_id}/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Mode */
        post: operations["set_mode_api_operate__flow_id___block_id__mode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/{flow_id}/{block_id}/sp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Sp */
        post: operations["set_sp_api_operate__flow_id___block_id__sp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/{flow_id}/{block_id}/mv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Mv */
        post: operations["set_mv_api_operate__flow_id___block_id__mv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operate/mpcs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Mpcs
         * @description Projeta os blocos MPC de todos os flows do projeto ativo (spec §4.1; decisão A-7).
         *
         *     Sem projeto ativo, lista vazia (§4.1-4) — não há 404, o recurso é a projeção do projeto
         *     vigente, não um flow identificado. Estado rodando/parado do flow não entra na projeção.
         */
        get: operations["list_mpcs_api_operate_mpcs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Eventos mais recentes primeiro; sem paginação (padrão F1 §6.1).
         */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Uma série por tag pedida, sempre; ordem temporal crescente (uPlot exige x monotônico).
         */
        get: operations["get_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/mpc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History Mpc
         * @description Histórico do bloco MPC (spec F5 §2.4): uma série por var_id pedida, sempre.
         *
         *     Validação de forma (`var_ids`/janela) roda antes de tocar o banco; só então o flow é
         *     carregado (404 se inexistente) e o bloco validado contra o `graph_json` (422 se
         *     inexistente ou não-`mpc`) — mesma ordem de `operate.py::_mpc_config`.
         */
        get: operations["get_history_mpc_api_history_mpc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/ssto/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History Ssto Last
         * @description Última execução do SSTO do bloco (ADR-027 §11) — cold-start do sumário do otimizador
         *     na Operação: sem ela o card ficaria vazio até o próximo ciclo do MPC (Ts_mpc pode ser
         *     minutos). 200 com `null` quando o bloco nunca executou o SSTO — mesmo contrato dos
         *     campos opcionais existentes, não 404 (o recurso é a última execução, não o bloco).
         */
        get: operations["get_history_ssto_last_api_history_ssto_last_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history-retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History Retention */
        get: operations["get_history_retention_api_history_retention_get"];
        /** Update History Retention */
        put: operations["update_history_retention_api_history_retention_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/app/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate App Cert
         * @description Gera o certificado autoassinado do worker; `force` substitui o existente (spec §5.7).
         */
        post: operations["generate_app_cert_api_certificates_app_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get App Cert
         * @description Metadados do certificado. Ausência não é erro: devolve `exists=false`, nunca 404.
         *
         *     Arquivo presente mas ilegível é outra coisa: falha de infraestrutura no volume, não
         *     entrada do usuário. Continua 500, mas mapeado — com mensagem em pt-BR dizendo qual é a
         *     saída — em vez de subir cru como erro genérico do framework.
         */
        get: operations["get_app_cert_api_certificates_app_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/app/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export App Cert
         * @description Download do `.der` para o operador cadastrar na trust list do servidor OPC-UA.
         */
        get: operations["export_app_cert_api_certificates_app_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppCertificateGenerateIn */
        AppCertificateGenerateIn: {
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** AppCertificateGenerateOut */
        AppCertificateGenerateOut: {
            /** Exists */
            exists: boolean;
            /** Subject */
            subject?: string | null;
            /** Fingerprint Sha256 */
            fingerprint_sha256?: string | null;
            /** Not Before */
            not_before?: string | null;
            /** Not After */
            not_after?: string | null;
            /** Application Uri */
            application_uri?: string | null;
            /** Warning */
            warning?: string | null;
        };
        /** AppCertificateOut */
        AppCertificateOut: {
            /** Exists */
            exists: boolean;
            /** Subject */
            subject?: string | null;
            /** Fingerprint Sha256 */
            fingerprint_sha256?: string | null;
            /** Not Before */
            not_before?: string | null;
            /** Not After */
            not_after?: string | null;
            /** Application Uri */
            application_uri?: string | null;
        };
        /** ConnectionCreate */
        ConnectionCreate: {
            /** Name */
            name: string;
            /** Endpoint */
            endpoint: string;
            /**
             * Security Policy
             * @default none
             * @enum {string}
             */
            security_policy: "none" | "basic256sha256";
            /**
             * Security Mode
             * @default none
             * @enum {string}
             */
            security_mode: "none" | "sign" | "sign_and_encrypt";
            /**
             * Auth Mode
             * @default anonymous
             * @enum {string}
             */
            auth_mode: "anonymous" | "user_password" | "certificate";
            /** Auth Username */
            auth_username?: string | null;
            /** Server Cert File */
            server_cert_file?: string | null;
            /** Project Id */
            project_id: number;
            /** Auth Password */
            auth_password?: string | null;
        };
        /** ConnectionOut */
        ConnectionOut: {
            /** Name */
            name: string;
            /** Endpoint */
            endpoint: string;
            /**
             * Security Policy
             * @default none
             * @enum {string}
             */
            security_policy: "none" | "basic256sha256";
            /**
             * Security Mode
             * @default none
             * @enum {string}
             */
            security_mode: "none" | "sign" | "sign_and_encrypt";
            /**
             * Auth Mode
             * @default anonymous
             * @enum {string}
             */
            auth_mode: "anonymous" | "user_password" | "certificate";
            /** Auth Username */
            auth_username?: string | null;
            /** Server Cert File */
            server_cert_file?: string | null;
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Has Password */
            has_password: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConnectionUpdate
         * @description Atualização parcial; a coerência é checada no router sobre o estado final.
         */
        ConnectionUpdate: {
            /** Name */
            name?: string | null;
            /** Endpoint */
            endpoint?: string | null;
            /** Security Policy */
            security_policy?: ("none" | "basic256sha256") | null;
            /** Security Mode */
            security_mode?: ("none" | "sign" | "sign_and_encrypt") | null;
            /** Auth Mode */
            auth_mode?: ("anonymous" | "user_password" | "certificate") | null;
            /** Auth Username */
            auth_username?: string | null;
            /** Auth Password */
            auth_password?: string | null;
            /** Server Cert File */
            server_cert_file?: string | null;
        };
        /**
         * ConstraintOut
         * @description Projeção de uma Restrição do bloco (spec §4.1-1) — sem `tss`/`priority`/`kind`.
         */
        ConstraintOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Eu */
            eu: string;
            range: components["schemas"]["Range"];
            /**
             * Objective
             * @enum {string}
             */
            objective: "none" | "maximize" | "minimize";
        };
        /**
         * CvOut
         * @description Projeção de uma CV do bloco (spec §4.1-1) — sem `weight`/`tss`/`kind` (§4.1-3).
         */
        CvOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Eu */
            eu: string;
            sp_limits: components["schemas"]["Limits"];
            /**
             * Objective
             * @enum {string}
             */
            objective: "none" | "maximize" | "minimize" | "observe_limit" | "target" | "psv";
        };
        /**
         * DvOut
         * @description Projeção de uma DV do bloco (spec §4.1-1) — `range` opcional (§4.2, RF-702).
         */
        DvOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Eu */
            eu: string;
            range?: components["schemas"]["Range"] | null;
        };
        /** EventOut */
        EventOut: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "alarm";
            /** Origin */
            origin: string;
            /** Message */
            message: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** FlowCreate */
        FlowCreate: {
            /** Project Id */
            project_id: number;
            /** Name */
            name: string;
            /**
             * Ts Seconds
             * @enum {unknown}
             */
            ts_seconds: 0.5 | 1 | 2 | 5 | 10 | 30 | 60;
        };
        /** FlowDetail */
        FlowDetail: {
            /**
             * Watchdog Enabled
             * @default false
             */
            watchdog_enabled: boolean;
            /** Watchdog Connection Id */
            watchdog_connection_id?: number | null;
            /** Watchdog Read Node Id */
            watchdog_read_node_id?: string | null;
            /** Watchdog Write Node Id */
            watchdog_write_node_id?: string | null;
            /**
             * Watchdog Period Ms
             * @default 1500
             */
            watchdog_period_ms: number;
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Name */
            name: string;
            /** Ts Seconds */
            ts_seconds: number;
            /**
             * Desired State
             * @enum {string}
             */
            desired_state: "running" | "stopped";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Graph Json */
            graph_json: {
                [key: string]: unknown;
            };
        };
        /**
         * FlowOut
         * @description Linha da lista (spec §5.1): sem `graph_json`, que por flow pode ser grande.
         */
        FlowOut: {
            /**
             * Watchdog Enabled
             * @default false
             */
            watchdog_enabled: boolean;
            /** Watchdog Connection Id */
            watchdog_connection_id?: number | null;
            /** Watchdog Read Node Id */
            watchdog_read_node_id?: string | null;
            /** Watchdog Write Node Id */
            watchdog_write_node_id?: string | null;
            /**
             * Watchdog Period Ms
             * @default 1500
             */
            watchdog_period_ms: number;
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Name */
            name: string;
            /** Ts Seconds */
            ts_seconds: number;
            /**
             * Desired State
             * @enum {string}
             */
            desired_state: "running" | "stopped";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * FlowSaved
         * @description Resposta do PUT (spec §5.2): avisos de inversão acompanham o flow gravado.
         */
        FlowSaved: {
            flow: components["schemas"]["FlowDetail"];
            /** Warnings */
            warnings?: string[];
        };
        /** FlowUpdate */
        FlowUpdate: {
            /** Name */
            name?: string | null;
            /** Ts Seconds */
            ts_seconds?: (0.5 | 1 | 2 | 5 | 10 | 30 | 60) | null;
            /** Graph Json */
            graph_json?: {
                [key: string]: unknown;
            } | null;
            /** Watchdog Enabled */
            watchdog_enabled?: boolean | null;
            /** Watchdog Connection Id */
            watchdog_connection_id?: number | null;
            /** Watchdog Read Node Id */
            watchdog_read_node_id?: string | null;
            /** Watchdog Write Node Id */
            watchdog_write_node_id?: string | null;
            /** Watchdog Period Ms */
            watchdog_period_ms?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthOut
         * @description Forma de `/health` (spec §3.3): as 5 chaves sempre presentes, tipadas para o OpenAPI
         *     carregar `redis_ok`/`db_ok` — antes a rota devolvia `dict` cru e o gerador de contratos
         *     (`frontend/openapi.json`/`api-types.ts`, tarefa 6.1) não tinha como nomear os campos.
         */
        HealthOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Redis Ok */
            redis_ok: boolean;
            /** Db Ok */
            db_ok: boolean;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "raw" | "1m";
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Series */
            series: components["schemas"]["HistorySeries"][];
        };
        /** HistoryRetentionOut */
        HistoryRetentionOut: {
            /** Retention Days */
            retention_days: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HistoryRetentionUpdate */
        HistoryRetentionUpdate: {
            /** Retention Days */
            retention_days: number;
        };
        /** HistorySeries */
        HistorySeries: {
            /** Tag Id */
            tag_id: number;
            /** T */
            t: string[];
            /** V */
            v: number[];
            /** Q */
            q: number[];
            /** V Min */
            v_min?: number[] | null;
            /** V Max */
            v_max?: number[] | null;
        };
        /**
         * Horizons
         * @description Horizontes derivados do multiplicador, Ts do flow e TSS das linhas (spec §2.2-5).
         */
        Horizons: {
            /** Ts Mpc */
            ts_mpc: number;
            /** Np */
            np: number;
            /** Nc */
            nc: number;
        };
        /**
         * Limits
         * @description Faixa `{min, max}` — limites de MV (`limits`) ou setpoint de CV (`sp_limits`).
         */
        Limits: {
            /** Min */
            min: number;
            /** Max */
            max: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginOut */
        LoginOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["UserOut"];
        };
        /** ModeCommand */
        ModeCommand: {
            /**
             * Axis
             * @enum {string}
             */
            axis: "local_remote" | "man_auto";
            /**
             * Value
             * @enum {string}
             */
            value: "local" | "remote" | "man" | "auto";
        };
        /** MpcHistoryResponse */
        MpcHistoryResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "raw" | "1m";
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Series */
            series: components["schemas"]["MpcHistorySeries"][];
        };
        /**
         * MpcHistorySeries
         * @description Mesma forma de `HistorySeries`, com `var_id` no lugar de `tag_id`; `sp`/`auto`
         *     alinhados a `t` (spec F5 §2.4) — sem `q`, que não existe em `mpc_samples`.
         */
        MpcHistorySeries: {
            /** Var Id */
            var_id: string;
            /** T */
            t: string[];
            /** V */
            v: number[];
            /** Sp */
            sp: (number | null)[];
            /** Auto */
            auto: boolean[];
            /** V Min */
            v_min?: number[] | null;
            /** V Max */
            v_max?: number[] | null;
        };
        /**
         * MpcNodeOut
         * @description Um bloco `mpc` projetado (spec §4.1-1) — sem `models`/pesos/TSS (§4.1-3); estado
         *     rodando/parado do flow não entra (§4.1-4).
         *
         *     `horizons` é derivado no servidor porque a projeção não expõe `tss` (§4.1-3): sem ele o
         *     cliente teria de duplicar a regra de `derive_horizons` com metade da entrada.
         */
        MpcNodeOut: {
            /** Flow Id */
            flow_id: number;
            /** Flow Name */
            flow_name: string;
            /** Flow Ts Seconds */
            flow_ts_seconds: number;
            /** Block Id */
            block_id: string;
            /** Name */
            name: string;
            /** Multiplier */
            multiplier: number;
            variables: components["schemas"]["MpcVariablesOut"];
            horizons: components["schemas"]["Horizons"];
        };
        /** MpcVariablesOut */
        MpcVariablesOut: {
            /** Mvs */
            mvs: components["schemas"]["MvOut"][];
            /** Cvs */
            cvs: components["schemas"]["CvOut"][];
            /** Constraints */
            constraints: components["schemas"]["ConstraintOut"][];
            /** Dvs */
            dvs: components["schemas"]["DvOut"][];
        };
        /** MvCommand */
        MvCommand: {
            /** Var Id */
            var_id: string;
            /** Value */
            value: number;
        };
        /**
         * MvOut
         * @description Projeção de uma MV do bloco (spec §4.1-1) — sem `pid`/`initial_value`/`psv` (§4.1-3).
         */
        MvOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Eu */
            eu: string;
            limits: components["schemas"]["Limits"];
            /** Du Max */
            du_max: number;
            /**
             * Objective
             * @enum {string}
             */
            objective: "none" | "maximize" | "minimize" | "psv" | "equalize";
        };
        /**
         * PendingSecretOut
         * @description Pendência de segredo de uma conexão importada (spec F6 §3.2-8, decisão A-4).
         */
        PendingSecretOut: {
            /** Connection Name */
            connection_name: string;
            /** Needs Password */
            needs_password: boolean;
            /** Needs Server Certificate */
            needs_server_certificate: boolean;
            /** Needs App Certificate */
            needs_app_certificate: boolean;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** ProjectImportOut */
        ProjectImportOut: {
            project: components["schemas"]["ProjectOut"];
            /** Pending Secrets */
            pending_secrets: components["schemas"]["PendingSecretOut"][];
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * Range
         * @description Faixa `{low, high}` de uma Restrição.
         */
        Range: {
            /** Low */
            low: number;
            /** High */
            high: number;
        };
        /** ServerCertificateOut */
        ServerCertificateOut: {
            /** Conn Id */
            conn_id: number;
            /** Server Cert File */
            server_cert_file: string;
            /** Fingerprint Sha256 */
            fingerprint_sha256: string;
        };
        /** SpCommand */
        SpCommand: {
            /** Var Id */
            var_id: string;
            /** Value */
            value: number;
        };
        /**
         * SstoLastOut
         * @description Última execução do SSTO de um bloco (`GET /api/history/ssto/last`) — cold-start do
         *     sumário do otimizador na Operação, sem esperar o próximo ciclo do MPC.
         */
        SstoLastOut: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            run: components["schemas"]["SstoRun"];
        };
        /**
         * SstoRun
         * @description Registro imutável de uma execução do SSTO (ADR-027 §11, RF-903).
         *
         *     Viaja como campo opcional de `MpcState` — **sem canal novo** (ADR-002): o recorder, que
         *     já assina `mpc.state.*` e é o único escritor de hypertable, o materializa em
         *     `ssto_runs`. Quadro sem SSTO omite o campo e continua idêntico ao da F5.
         *
         *     Carrega os dois hashes que amarram o registro ao que produziu aquele alvo:
         *     `config_hash` (custos, limites, ranks) e `model_hash` (a matriz de ganho usada).
         *
         *     `cv_target` de linha `integrating` é uma TAXA [EU/s], não um nível (ADR-027 §4).
         */
        SstoRun: {
            /** Run Id */
            run_id: string;
            /** Config Hash */
            config_hash: string;
            /** Model Hash */
            model_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "optimal" | "relaxed" | "infeasible" | "unbounded" | "error";
            /** Solver */
            solver: string;
            /** Solve Ms */
            solve_ms: number;
            /** Objective */
            objective: number;
            /** Mv */
            mv: {
                [key: string]: number;
            };
            /** Cv Ss */
            cv_ss: {
                [key: string]: number;
            };
            /** Bias */
            bias: {
                [key: string]: number;
            };
            /** Dv */
            dv: {
                [key: string]: number;
            };
            /** Costs */
            costs: {
                [key: string]: number;
            };
            /** Delta Mv */
            delta_mv: {
                [key: string]: number;
            };
            /** Mv Target */
            mv_target: {
                [key: string]: number;
            };
            /** Cv Target */
            cv_target: {
                [key: string]: number;
            };
            /** Given Up */
            given_up: string[];
            /** Active Constraints */
            active_constraints: string[];
            /** Duals */
            duals: {
                [key: string]: number;
            };
        };
        /** TagCreate */
        TagCreate: {
            /** Connection Id */
            connection_id: number;
            /** Name */
            name: string;
            /** Node Id */
            node_id: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "r" | "w";
            /**
             * Data Type
             * @enum {string}
             */
            data_type: "float" | "int" | "bool";
            /**
             * Eu
             * @default
             */
            eu: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** TagOut */
        TagOut: {
            /** Id */
            id: number;
            /** Connection Id */
            connection_id: number;
            /** Name */
            name: string;
            /** Node Id */
            node_id: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "r" | "w";
            /**
             * Data Type
             * @enum {string}
             */
            data_type: "float" | "int" | "bool";
            /** Eu */
            eu: string;
            /** Description */
            description: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TagUpdate */
        TagUpdate: {
            /** Name */
            name?: string | null;
            /** Node Id */
            node_id?: string | null;
            /** Direction */
            direction?: ("r" | "w") | null;
            /** Data Type */
            data_type?: ("float" | "int" | "bool") | null;
            /** Eu */
            eu?: string | null;
            /** Description */
            description?: string | null;
        };
        /** UserCreate */
        UserCreate: {
            /** Username */
            username: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "operator";
        };
        /**
         * UserOut
         * @description Usuário exposto pela API — nunca inclui password_hash.
         */
        UserOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "operator";
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Password */
            password?: string | null;
            /** Role */
            role?: ("admin" | "operator") | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    health_workers_api_health_workers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_project_api_projects__project_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_api_projects__project_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_project_api_projects_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Name */
                    name?: string | null;
                    /** Bundle */
                    bundle: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectImportOut"];
                };
            };
        };
    };
    list_connections_api_connections_get: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_connection_api_connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connection_api_connections__connection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_api_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_connection_api_connections__connection_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_server_certificate_api_connections__connection_id__server_certificate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerCertificateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_server_certificate_api_connections__connection_id__server_certificate_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: {
                connection_id?: number | null;
                direction?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tag_api_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tag_api_tags__tag_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_api_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flows_api_flows_get: {
        parameters: {
            query?: {
                project_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_flow_api_flows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_flow_api_flows__flow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_flow_api_flows__flow_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowSaved"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_flow_api_flows__flow_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deploy_flow_api_flows__flow_id__deploy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_flow_api_flows__flow_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_mode_api_operate__flow_id___block_id__mode_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: number;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModeCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_sp_api_operate__flow_id___block_id__sp_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: number;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_mv_api_operate__flow_id___block_id__mv_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flow_id: number;
                block_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MvCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mpcs_api_operate_mpcs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MpcNodeOut"][];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                severity?: ("info" | "warning" | "alarm") | null;
                origin?: string | null;
                start?: string | null;
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_history_get: {
        parameters: {
            query: {
                tag_ids: string;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_mpc_api_history_mpc_get: {
        parameters: {
            query: {
                flow_id: number;
                block_id: string;
                var_ids: string;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MpcHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_ssto_last_api_history_ssto_last_get: {
        parameters: {
            query: {
                flow_id: number;
                block_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SstoLastOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_retention_api_history_retention_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryRetentionOut"];
                };
            };
        };
    };
    update_history_retention_api_history_retention_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryRetentionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryRetentionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_app_cert_api_certificates_app_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AppCertificateGenerateIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppCertificateGenerateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_cert_api_certificates_app_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppCertificateOut"];
                };
            };
        };
    };
    export_app_cert_api_certificates_app_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
